using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BooksApi.Models.Book
{
    /// <summary>
    /// GroupTest - nhóm thành viên
    /// </summary>
    [BsonIgnoreExtraElements]
    public class GroupTest
    {
        /// <summary>
        /// Object Id
        /// </summary>
        [BsonId] //document's primary key
        [BsonRepresentation(BsonType.ObjectId)]//allow passing the parameter as type string instead of an ObjectId structure
        // standard BSonId generated by MongoDb
        public string Id { get; set; }
        /// <summary>
        /// mã Nhóm thành viên
        /// </summary>
        //======YÊU CẦU=============
        [Display(Name = "Mã Nhóm")]
        [Required(ErrorMessage = "{0} Không Được Để Trống !")]
        [BsonRequired]
        [MinLength(2, ErrorMessage = "{0}, tối thiểu phải {1} kí tự")]
        public string Code { get; set; }
        /// <summary>
        /// Tên Nhóm thành viên
        /// </summary>
        [Display(Name = "Tên Nhóm")]
        [Required(ErrorMessage = "{0} Không Được Để Trống !")]
        [BsonRequired]
        public string Name { get; set; }
        /// <summary>
        /// Mô tả chi tiết thông tin nhóm thành viên
        /// </summary>
        [Display(Name = "Mô Tả Nhóm")]
        [BsonDefaultValue("")]
        public string Desc { get; set; }
        /// <summary>
        /// nhóm danh sách chức năng - Code
        /// </summary>
        [Display(Name = "Ds Mã chức năng")]
        public string[] ArrFunctionId { get; set; }

        /// <summary>
        /// Nhóm chức năng
        /// </summary>
        [BsonIgnore]
        [BsonExtraElements]
        public List<SystemFunctionTest> ArrFunction { get; set; }

        /// <summary>
        /// Ds Menu
        /// </summary>
        [Display(Name = "Ds Menu")]
        public string[] ArrMenuId { get; set; }

        //==============================================
        /// <summary>
        /// Trạng thái, mặc định = 0
        /// </summary>
        [BsonRepresentation(BsonType.Int32)]
        public int Status { get; set; } = 0;
        /// <summary>
        /// Đang Active không? mặc định = true là đang active
        /// </summary>
        public bool IsActive { get; set; } = true;
        /// <summary>
        /// Tạo bởi ai
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// Thời điểm tạo
        /// </summary>
        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Sửa / Xóa bởi ai
        /// </summary>
        public string UpdatedBy { get; set; }
        /// <summary>
        /// thời điểm sửa/xóa
        /// </summary>
        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        public DateTime UpdatedOn { get; set; }
    }
}
